---
- hosts: docker
  become: true
  tasks:
    - name: instala dipendencias
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: repositorio chave GPG
      apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

    - name: chave repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: instala docker
      apt:
       name: "{{item}}"
       state: latest
       update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: docker ativo
      service:
        name: docker
        state: started
        enabled: yes

    - name: add usuario ao docker
      user:
       name: ubuntu
       groups: docker
       state: present
       append: yes

  handlers:
      - name: restart docker
        service:
          name: docker
          state: restarted
