---
- hosts: all
  handlers:
  become: yes
  tasks:
    - name: Upgrade all packages, excluding kernel & foo related packages
      apt:
        name: '*'
        update_cache: true
        update_only: true


    - name: 'Instala Pacotes de Dependencia '
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
      - nginx
      - php

    - name: 'Baixa o arquivo de instalacao do Wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'

    - name: 'Descompacta o wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/
        remote_src: yes
      become: yes

    - copy:
       src: '/var/www/wordpress/wp-config-sample.php'
       dest: '/var/www/wordpress/wp-config.php'
       remote_src: yes
      become: yes

    - name: 'Configura o wp-config com as entradas do banco de dados'
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'admin'}
        - { regex: 'password_here', value: 'masteradmin'}
        - { regex: 'localhost', value: '192.168.56.7'}
      become: yes
